services:
  postgres:
    image: postgres:15           # Changed from postgres:15-alpine
    container_name: server-monitor-db
    environment:
      POSTGRES_DB: server_monitor
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: monitor_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: